"""Build helpers for packaging the launcher executable."""

from __future__ import annotations

import argparse
import platform
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from .config import load_config

DEFAULT_CONFIG_PATH = Path("packaging/launcher/application.yml")
DEFAULT_OUTPUT_DIR = Path("dist/launcher")
DEFAULT_BUILD_DIR_NAME = "build"
DEFAULT_SPEC_NAME = "launcher.spec"
DEFAULT_ENTRY_NAME = "launcher_build_entry.py"


@dataclass(frozen=True)
class BuildPlan:
    """Resolved inputs for a launcher build."""

    config_path: Path
    output_dir: Path
    spec_path: Path
    entry_path: Path
    app_name: str
    datas: list[tuple[str, str]]
    icon_path: Path | None = None
    uses_custom_spec: bool = False


class BuildCliError(Exception):
    """Raised when a launcher build cannot be planned or executed."""


def create_build_plan(
    *,
    config_path: Path | None = None,
    output_dir: Path = DEFAULT_OUTPUT_DIR,
    spec_path: Path | None = None,
    icon_path: Path | None = None,
) -> BuildPlan:
    """Resolve build inputs without invoking PyInstaller."""
    config_path = (config_path or DEFAULT_CONFIG_PATH).expanduser()
    if not config_path.is_file():
        raise BuildCliError(f"Config file not found: {config_path}")

    try:
        config = load_config(config_path)
    except (OSError, ValueError) as exc:
        raise BuildCliError(f"Invalid config {config_path}: {exc}") from exc
    app_name = config.name

    config_dir = config_path.parent
    datas = [(config_path.resolve().as_posix(), "packaging/launcher")]

    icon_path = _resolve_icon(icon_path) if icon_path else _find_icon(config_dir)
    if icon_path:
        icon_path = icon_path.resolve()
        datas.append((icon_path.as_posix(), "resources"))

    output_dir = output_dir.expanduser().resolve()
    build_dir = output_dir / DEFAULT_BUILD_DIR_NAME
    custom_spec = spec_path is not None
    spec_path = spec_path.expanduser().resolve() if spec_path else build_dir / DEFAULT_SPEC_NAME
    return BuildPlan(
        config_path=config_path.resolve(),
        output_dir=output_dir,
        spec_path=spec_path,
        entry_path=build_dir / DEFAULT_ENTRY_NAME,
        app_name=app_name,
        datas=datas,
        icon_path=icon_path,
        uses_custom_spec=custom_spec,
    )


def write_generated_files(plan: BuildPlan) -> None:
    """Write the temporary entry point and generated PyInstaller spec."""
    plan.entry_path.parent.mkdir(parents=True, exist_ok=True)
    plan.entry_path.write_text(
        "\n".join(
            [
                "# Generated by `launcher build`; do not edit by hand.",
                "from launcher.main import main",
                "",
                "raise SystemExit(main())",
                "",
            ]
        )
    )
    if not plan.uses_custom_spec:
        plan.spec_path.write_text(render_spec(plan))


def render_spec(plan: BuildPlan) -> str:
    """Render a PyInstaller spec for the launcher executable."""
    datas = ",\n        ".join(repr((src, dest)) for src, dest in plan.datas)
    icon_expr = "None"
    if plan.icon_path:
        icon_expr = repr(plan.icon_path.as_posix())

    return "\n".join(
        [
            "# -*- mode: python ; coding: utf-8 -*-",
            "# Generated by `launcher build`; edit packaging inputs instead.",
            f"# Output directory: {_relative_source(plan.output_dir.as_posix())}",
            "import platform",
            "",
            "a = Analysis(",
            f"    [{plan.entry_path.as_posix()!r}],",
            "    pathex=[],",
            "    binaries=[],",
            f"    datas=[{datas}],",
            "    hiddenimports=[],",
            "    hookspath=[],",
            "    hooksconfig={},",
            "    runtime_hooks=[],",
            "    excludes=[],",
            "    noarchive=False,",
            "    optimize=0,",
            ")",
            "pyz = PYZ(a.pure)",
            "",
            "exe = EXE(",
            "    pyz,",
            "    a.scripts,",
            "    [],",
            "    exclude_binaries=True,",
            f"    name={_executable_name(plan.app_name)!r},",
            "    debug=False,",
            "    bootloader_ignore_signals=False,",
            "    strip=False,",
            "    upx=True,",
            "    console=False,",
            "    disable_windowed_traceback=False,",
            "    argv_emulation=False,",
            "    target_arch=None,",
            "    codesign_identity=None,",
            "    entitlements_file=None,",
            f"    icon={icon_expr},",
            ")",
            "coll = COLLECT(",
            "    exe,",
            "    a.binaries,",
            "    a.datas,",
            "    strip=False,",
            "    upx=True,",
            "    upx_exclude=[],",
            f"    name={_executable_name(plan.app_name)!r},",
            ")",
            "if platform.system() == 'Darwin':",
            "    app = BUNDLE(",
            "        coll,",
            f"        name={plan.app_name + '.app'!r},",
            f"        icon={icon_expr},",
            "        bundle_identifier=None,",
            "    )",
            "",
        ]
    )


def run_pyinstaller(plan: BuildPlan) -> None:
    """Run PyInstaller for a resolved build plan."""
    executable = shutil.which("pyinstaller")
    if not executable:
        raise BuildCliError("PyInstaller is required. Run with `uv run --with pyinstaller launcher build`.")

    command = [
        executable,
        "--clean",
        "--noconfirm",
        "--distpath",
        plan.output_dir.as_posix(),
        "--workpath",
        (plan.output_dir / DEFAULT_BUILD_DIR_NAME / "pyinstaller").as_posix(),
        plan.spec_path.as_posix(),
    ]
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        raise BuildCliError(
            f"PyInstaller failed with exit code {e.returncode}.\n\n"
            f"Command:\n  {format_shell_command(command)}"
        ) from e


def build_parser() -> argparse.ArgumentParser:
    """Build the parser for `launcher build`."""
    parser = argparse.ArgumentParser(
        prog="launcher build",
        description="Build a packaged launcher executable for this app.",
    )
    parser.add_argument("--config", type=Path, default=None, help="Launcher app config")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT_DIR, help="Launcher build output directory")
    parser.add_argument("--spec", type=Path, default=None, help="Use an explicit PyInstaller spec")
    parser.add_argument("--icon", type=Path, default=None, help="Icon for generated PyInstaller spec")
    parser.add_argument("--spec-only", action="store_true", help="Write generated build files without running PyInstaller")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run `launcher build`."""
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.icon and args.spec:
            raise BuildCliError("--icon cannot be used with --spec because icon paths are encoded in the spec")
        plan = create_build_plan(config_path=args.config, output_dir=args.out, spec_path=args.spec, icon_path=args.icon)
        write_generated_files(plan)
        if args.spec_only:
            print("Spec-only mode: generated build files without running PyInstaller.")
        else:
            print("Running PyInstaller...")
            run_pyinstaller(plan)
            print(f"Build complete: packaged launcher files are in {plan.output_dir}")
        print(f"Launcher build spec: {plan.spec_path}")
        print(f"Launcher build output: {plan.output_dir}")
        return 0
    except BuildCliError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    return 1


def format_shell_command(command: Sequence[str]) -> str:
    """Render a command for copy/paste-friendly CLI output."""
    return " ".join(shlex.quote(part) for part in command)


def _find_icon(config_dir: Path) -> Path | None:
    if platform.system() == "Darwin":
        names = ("app.icns", "icon_128x128.png")
    elif platform.system() == "Windows":
        names = ("app.ico", "icon_128x128.png", "app.icns")
    else:
        names = ("icon_128x128.png", "app.icns", "app.ico")

    for name in names:
        path = config_dir / name
        if path.is_file():
            return path
    return None


def _resolve_icon(icon_path: Path) -> Path:
    icon_path = icon_path.expanduser()
    if not icon_path.is_file():
        raise BuildCliError(f"Icon file not found: {icon_path}")
    return icon_path


def _executable_name(app_name: str) -> str:
    name = "".join(char.lower() if char.isalnum() else "-" for char in app_name)
    return "-".join(part for part in name.split("-") if part) or "launcher"


def _relative_source(path: str) -> str:
    source = Path(path)
    try:
        return source.resolve().relative_to(Path.cwd().resolve()).as_posix()
    except ValueError:
        return source.as_posix()
